# Generated by Django 4.1.3 on 2026-01-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskactivity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='taskactivity',
            name='performed_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
